language: rust
rust:
        - stable

sudo: required
services:
        - docker

before_install:
        - cargo install cross

script:
        - cargo test
        - cross build --target x86_64-unknown-linux-gnu
        - cross build --target x86_64-unknown-freebsd
        - cross build --target x86_64-sun-solaris
        - cross build --target x86_64-pc-windows-gnu
