language: rust
rust:
        - stable

sudo: required
services:
        - docker

before_install:
        - rustup component add rustfmt-preview
        - cargo install cross

script:
        - cargo fmt --all -- --check
        - cargo test
        - cross build --target x86_64-unknown-freebsd
        - cross build --target x86_64-pc-windows-gnu
        - cross build --target x86_64-sun-solaris
